name: lean_coffee_timer
description: Lean Coffee Toolbox.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: ^1.0.0
  path_provider: any
  flutter_launcher_icons: ^0.7.0
  provider: ^2.0.0
  global_configuration: ^1.4.0
  audioplayers: ^0.13.2
  uuid: 2.0.1
  equatable: ^0.2.3
  meta: ^1.1.6
  intl: ^0.16.0 
  flutter_form_builder: ^3.5.5
  flutter_staggered_grid_view: ^0.3.0
  auto_size_text: ^1.1.2
  share: ^0.6.1
  barcode_scan: ^0.0.4
  qr_flutter: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/Icon.png
    - assets/cfg/
    - assets/analogwatch.mp3
    - assets/oldschoolbell.mp3
    - assets/smokealarm.mp3
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "images/Icon.png"